apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeploy
  namespace: registration
spec:
  strategy:
    type: RollingUpdate
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: javawebapp 
        image: vishnukrn/java-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service
metadata:
  name: javawebsvc
  namespace: registration
spec: 
  type: NodePort
  selector:
    app: java
  ports:
  - port: 8080
    targetPort: 8080
